// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJA8AlWwEnWKTyRtb7J9jb6qxdKeStL1c',
    appId: '1:1020001715603:web:70722b8b3776b8a547d466',
    messagingSenderId: '1020001715603',
    projectId: 'duongketoai-df4c7',
    authDomain: 'duongketoai-df4c7.firebaseapp.com',
    storageBucket: 'duongketoai-df4c7.appspot.com',
    measurementId: 'G-BL4XWFNTF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrt1pBM2KXdr_n-4qER_TeQbdKUyfghcE',
    appId: '1:1020001715603:android:6ceb176b533d30c347d466',
    messagingSenderId: '1020001715603',
    projectId: 'duongketoai-df4c7',
    storageBucket: 'duongketoai-df4c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCy3RI0zIiCxlMLONxzCG8vjPN3Djd7Y',
    appId: '1:1020001715603:ios:0d8ea5c68ce575a447d466',
    messagingSenderId: '1020001715603',
    projectId: 'duongketoai-df4c7',
    storageBucket: 'duongketoai-df4c7.appspot.com',
    androidClientId: '1020001715603-a48uv9mhjpvsbfb9i90iafi6mkme3kh3.apps.googleusercontent.com',
    iosClientId: '1020001715603-588eg08d3us3kbg8o9r14kj9eiotgns4.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCy3RI0zIiCxlMLONxzCG8vjPN3Djd7Y',
    appId: '1:1020001715603:ios:0d8ea5c68ce575a447d466',
    messagingSenderId: '1020001715603',
    projectId: 'duongketoai-df4c7',
    storageBucket: 'duongketoai-df4c7.appspot.com',
    androidClientId: '1020001715603-a48uv9mhjpvsbfb9i90iafi6mkme3kh3.apps.googleusercontent.com',
    iosClientId: '1020001715603-588eg08d3us3kbg8o9r14kj9eiotgns4.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJA8AlWwEnWKTyRtb7J9jb6qxdKeStL1c',
    appId: '1:1020001715603:web:780c3f5e76f7d00b47d466',
    messagingSenderId: '1020001715603',
    projectId: 'duongketoai-df4c7',
    authDomain: 'duongketoai-df4c7.firebaseapp.com',
    storageBucket: 'duongketoai-df4c7.appspot.com',
    measurementId: 'G-5KBS2XX72F',
  );
}
